version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true  
      - GF_LOG_LEVEL=warn     
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - "thanos_query_frontend"  
    volumes:
      - ./grafana-ds.yaml:/etc/grafana/provisioning/datasources/grafana-ds.yaml

  memcached:
    image: memcached
    command:
      - -I 5m
    ports:
      - '11211:11211'    

  thanos_query:
    image: thanosio/thanos:v0.26.0
    container_name: thanos_query
    command:
      - query
      - --log.level=info
      - --log.format=logfmt
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:9091
      - --store=thanos.local.dev:443
      - --grpc-client-tls-secure
      - --grpc-client-tls-ca=/etc/ca.crt
      - --grpc-client-tls-key=/etc/tls.key
      - --grpc-client-tls-cert=/etc/tls.crt
    ports:
      - "10091:10091"
      - "9091:9091"
    volumes:
      - ./ssl/ca.crt:/etc/ca.crt
      - ./ssl/tls.key:/etc/tls.key
      - ./ssl/tls.crt:/etc/tls.crt

  thanos_query_frontend:
    image: thanosio/thanos:v0.26.0
    container_name: thanos_query_frontend
    command:
      - query-frontend
      - --log.level=info
      - --log.format=logfmt
      - --http-address=0.0.0.0:9090
      - --query-range.partial-response
      - --query-frontend.downstream-url=http://thanos_query:9091
      - --query-range.split-interval=1h
      - --query-range.max-retries-per-request=5
      - --query-frontend.log-queries-longer-than=5s
      - --cache-compression-type=snappy    
      - |-
        --query-range.response-cache-config="config":
           "addresses":
             - "memcached:11211"
           "max_async_buffer_size": 5000
           "max_async_concurrency": 20
           "max_get_multi_batch_size": 0
           "max_get_multi_concurrency": 100
           "max_idle_connections": 100
           "max_item_size": "5MB"
           "timeout": "500ms"
        "type": "memcached"
      - |-
        --labels.response-cache-config="config":
          "addresses":
            - "memcached:11211"
          "max_async_buffer_size": 5000
          "max_async_concurrency": 20
          "max_get_multi_batch_size": 0
          "max_get_multi_concurrency": 100
          "max_idle_connections": 100          
          "max_item_size": "5MB"
          "timeout": "500ms"
        "type": "memcached"        
    ports:
      - "9090:9090" 
    links:
      - "thanos_query"     
      - "memcached"